limit_req_zone $binary_remote_addr zone=rl:10m rate=5r/s;

server {
    include /etc/letsencrypt/options-ssl-nginx.conf;

    listen 443 ssl;
    listen 443 quic;
    server_name randomdomen.ru;
    root /var/lib/www/html/default;

    http2 on;
    http3 on;
    quic_gso on;
    quic_retry on;

    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    ssl_certificate /etc/letsencrypt/live/randomdomen.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/randomdomen.ru/privkey.pem; # managed by Certbot

    add_header Alt-Svc 'h3=":443"; ma=86400';

    location / {
        try_files $uri $uri/ /index.html;

        limit_req zone=rl burst=2 nodelay;
    }

    location /api/ {
        proxy_pass http://api:3000$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        limit_req zone=rl burst=2 nodelay;
    }
}

server {
    listen 80 default_server;
    server_name randomdomen.ru;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    include /etc/letsencrypt/options-ssl-nginx.conf;

    listen 443 ssl;
    listen 443 quic;
    server_name dash.randomdomen.ru;

    http2 on;
    http3 on;
    quic_gso on;
    quic_retry on;

    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    ssl_certificate /etc/letsencrypt/live/randomdomen.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/randomdomen.ru/privkey.pem; # managed by Certbot

    add_header Alt-Svc 'h3=":443"; ma=86400';

    location / {
        proxy_pass http://grafana:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        limit_req zone=rl burst=2 nodelay;
    }

    location /nginx_status {
        stub_status;
        allow 127.0.0.1;
        allow 172.0.0.0/8;
        deny all;
    }
}

server {
    listen 80;
    server_name dash.randomdomen.ru;

    location / {
        return 301 https://$host$request_uri;
    }
}

